# ==========================================
# RESOURCE GROUP
# ==========================================
# Creates the base architectural logical perimeter inside your Azure subscription.
resource "azurerm_resource_group" "rg" {
  name     = var.resource_group_name
  location = var.location
}

# ==========================================
# STORAGE ACCOUNT
# ==========================================
# Provisions the physical storage hardware cluster required to store files.
resource "azurerm_storage_account" "storage" {
  name                     = var.storage_account_name
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  
  # 'Standard' maps to standard HDD/SSD backing plates (cost-effective).
  # 'LRS' (Locally Redundant Storage) replicates data 3 times inside a single local datacenter.
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

# ==========================================
# STATIC WEBSITE CAPABILITY ACTIVATION
# ==========================================
# Decoupled resource that explicitly triggers the web server capabilities of the storage account.
resource "azurerm_storage_account_static_website" "website" {
  storage_account_id = azurerm_storage_account.storage.id
  index_document     = "index.html" # Instructs Azure what file to serve at the root URL
}

# ==========================================
# AUTOMATED FILE DEPLOYMENT (BLOB STORAGE)
# ==========================================
# This resource automatically reads your local 'index.html' file and pushes it
# into the hidden '$web' container generated by the static website resource.
resource "azurerm_storage_blob" "html_upload" {
  name                   = "index.html"
  storage_account_name   = azurerm_storage_account.storage.name
  
  # Dependency Chain: Must target '$web', which is created by the static_website resource.
  storage_container_name = "$web" 
  type                   = "Block"
  
  # Absolute reference to your local system file location relative to this folder root
  source                 = "./index.html" 
  
  # Overwrites the content-type metadata so browsers render the page instead of downloading it
  content_type           = "text/html" 

  # EXPLICIT DEPENDENCY: Forces Terraform to wait until Azure has 
  # fully activated the website feature and created the hidden $web container.
  depends_on = [
    azurerm_storage_account_static_website.website
  ]
}