# ==========================================
# OUTPUT VALUES (EXPORTED METADATA)
# ==========================================
# Outputs print operational results to the console window after an 'apply' operation.
# They are vital for automating configurations across multi-tier setups.

output "website_url" {
  description = "The public, globally accessible URL of your newly provisioned web asset."
  # Resolves dynamically by pulling the primary URL generated by the static website feature
  value       = azurerm_storage_account.storage.primary_web_endpoint
}